name: Build Android APK
on: { workflow_dispatch: {} }

# Juste ce qu'il faut : lecture du code
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # CLONE MANUEL — PUBLIC
      - name: Clone (public)
        if: ${{ github.event.repository.private == false }}
        run: |
          git init .
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch --depth=1 origin ${{ github.ref_name }}
          git checkout -qf FETCH_HEAD

      # CLONE MANUEL — PRIVÉ
      - name: Clone (private)
        if: ${{ github.event.repository.private }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git init .
          git remote add origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git fetch --depth=1 origin ${{ github.ref_name }}
          git checkout -qf FETCH_HEAD

      # BUILD ANDROID (action Buildozer officielle)
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer android debug

      # ARTEFACT : APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RetourSlog-android-debug-apk
          path: ${{ steps.buildozer.outputs.filename }}
